# Generated by Django 5.0.3 on 2024-04-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerycategory_alter_gallery_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
    ]
