# Generated by Django 5.0.3 on 2024-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_gallery_unique_position_per_each_category_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycategory',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
