# Generated by Django 5.0.3 on 2024-04-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_gallerycategory_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
