# Generated by Django 5.0.3 on 2024-04-28 19:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headexpression',
            name='expression',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='underchefsexpression',
            name='expression',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
