# Generated by Django 5.0.3 on 2024-05-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_alter_headexpression_expression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headexpression',
            name='expression',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='underchefsexpression',
            name='expression',
            field=models.TextField(),
        ),
    ]
