# Generated by Django 5.0.3 on 2024-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('phrase', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='StoryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='story_photos/')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'ordering': ('position',),
            },
        ),
    ]
