# Generated by Django 5.0.3 on 2024-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_ingredient', models.CharField(max_length=50)),
                ('second_ingredient', models.CharField(max_length=50)),
                ('third_ingredient', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='popular_menu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Popular Dishes',
                'ordering': ('-created_at',),
            },
        ),
    ]
