# Generated by Django 5.0.3 on 2024-04-30 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phrase', models.TextField()),
                ('photo_chef', models.ImageField(upload_to='about/about_restaurant/')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('mark', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('autor_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('authentic_phrase', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Restaurant',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='AboutSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_hor', models.ImageField(upload_to='about/slider/')),
                ('photo_vert', models.ImageField(upload_to='about/slider/')),
                ('phrase', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'About Slider',
                'ordering': ('position',),
            },
        ),
    ]
