# Generated by Django 5.0.3 on 2024-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutspecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='about/about_awards/')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'About Awards',
                'ordering': ('position',),
            },
        ),
    ]
