# Generated by Django 5.0.3 on 2024-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutawards_options_alter_aboutslider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutawards',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
