# Generated by Django 5.0.3 on 2024-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutawards_title_aboutawards_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBottomSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about/bottom_slider/')),
                ('title', models.CharField(max_length=255)),
                ('phrase', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bottom Slider',
                'ordering': ('position',),
            },
        ),
    ]
