# Generated by Django 5.0.3 on 2024-04-27 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_specialproposals_alter_menudish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialproposals',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
