# Generated by Django 5.0.3 on 2024-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_slag_menucategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudish',
            name='photo',
            field=models.ImageField(blank=True, upload_to='menu_dishes/'),
        ),
    ]
