# Generated by Django 5.0.3 on 2024-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menucategory_options_alter_menudish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
